use_frameworks!

target 'LinkDetect_Example' do
  pod 'LinkDetect', :path => '../'

  target 'LinkDetect_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
